### ISSUE TITLE
Unable to create Subscription CR from Argo workflow

### ISSUE THREAD

**Issue by aviweit** [open-cluster-management-io/multicloud-operators-subscription#32] opened 2021-09-27 18:18 UTC
Hi,

I would like to be able to orchestrate Subscription creation from via Argo. 

I have three clusters in my environment:

1. open-cluster-management hub
2. 'paris-core' cluster
3. 'paris-2' cluster

I am following the example at https://github.com/open-cluster-management-io/multicloud-operators-subscription/tree/main/examples/remote-git-sub. I can successfully apply the yamls and notice nginx deployment.

However, when I create the subscription from via Hub cluster Argo (`argo submit ./wf.yaml -n 5g-core  --watch`), it does not work; the the nginx is properly deployed into paris-core but the subscription CR get **unexpectedly deleted** from the managed cluster.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: example-from-argo-acm
spec:
  entrypoint: handlerequest
  arguments:
    parameters:
    - name: cluster_core
      value: paris-core

  templates:
  - name: handlerequest
    dag:
      tasks:
      - name: create-example-subscription
        template: create-example-subscription

  - name: create-example-subscription
    resource:
      action: create
      setOwnerReference: true
      manifest: |
        apiVersion: apps.open-cluster-management.io/v1
        kind: Subscription
        metadata:
          annotations:
            apps.open-cluster-management.io/github-branch: main
            apps.open-cluster-management.io/github-path: examples/remote-git-sub-op
          name: {{workflow.name}}
        spec:
          channel: gitops-chn-ns/gitops
          placement:
            clusters:
            - name: {{workflow.parameters.cluster_core}}
```

How can I fix this issue?

Thanks in advance.

**Comment by mikeshng** [comment] 2021-09-27 19:17
Hi, this seems like an Argo issue since you were able to get it all working without Argo. But I do have some suggestions:
Can you see the subscription CR in the managed cluster initially?
If you do, I suggest you manually add a dummy finalizer which will block the subscription resource from being removed.
Then you can do a `kubectl get -o yaml` on the subscription CR and inside the `managedFields`, hopefully it will show which controller is responsible for deleting it.

Just a FYI, we are working on a better integration with Argo using:
https://argoproj.github.io/argo-cd/user-guide/application-set
https://github.com/open-cluster-management/multicloud-integrations <- currently in midstream soon to be onboard to this upstream `-io` org.
With this integration, it allows you to do something like this using `clusterDecisionResource`

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: xxxxyyyyyzzzzzzzz
  namespace: xxxxyyyyyzzzzzzzz
  resourceVersion: '272080999'
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: ocm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: mike-test-placement
        requeueAfterSeconds: 30
  template:
    metadata:
      name: ocm-test2-{{name}}
    spec:
      destination:
        namespace: ocm-test
        server: '{{server}}'
      project: default
      source:
        path: xxxxyyyyyzzzzzzzz
        repoURL: https://github.com/xxxxyyyyyzzzzzzzz/app-samples
        targetRevision: main
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
```

**Comment by aviweit** [comment] 2021-09-27 19:17
It seems that Argo has the correct permissions as I can see the flow completes successfully.

```
Name:                example-from-argo-acm
Namespace:           5g-core
ServiceAccount:      default
Status:              Succeeded
Conditions:
 Completed           True
Created:             Mon Sep 27 19:13:59 +0000 (4 seconds ago)
Started:             Mon Sep 27 19:13:59 +0000 (4 seconds ago)
Finished:            Mon Sep 27 19:14:03 +0000 (now)
Duration:            4 seconds
Progress:            1/1
ResourcesDuration:   0s*(1 cpu),0s*(100Mi memory)
Parameters:
  cluster_core:      paris-core

STEP                              TEMPLATE                     PODNAME                           DURATION  MESSAGE
 ✔ example-from-argo-acm          handlerequest
 └─✔ create-example-subscription  create-example-subscription  example-from-argo-acm-2404421881  2s
```

and the subscription created in hub

```
kubectl  get subscriptions.apps.open-cluster-management.io  --all-namespaces
NAMESPACE   NAME                    STATUS       AGE   LOCAL PLACEMENT   TIME WINDOW
5g-core     example-from-argo-acm   Propagated   92s
```

but get deleted unexpectedly at the managed cluster.

Thanks.

**Comment by mikeshng** [comment] 2021-09-27 19:32
Hi, maybe we posted comments at the exact same time but did you get a chance to try and find out what is deleted the managed cluster subscription? 
https://github.com/open-cluster-management-io/multicloud-operators-subscription/issues/32#issuecomment-928195863

**Comment by mikeshng** [comment] 2021-09-27 19:49
Another thing to check is if you go to the `paris-core` namespace there should be a `deployable` resource there.
Could you provide the yaml output for that? This resource is responsible for creating that managed cluster subscription.

FYI, we are also under a heavy rework right now to deprecate the use of deployable api and use the `work` API instead. https://github.com/open-cluster-management-io/community/issues/64

**Comment by aviweit** [comment] 2021-09-27 19:57
Hi, I tried to setup a dummy finalizer via the below command but the CR get deleted.

```
kubectl patch crd/subscriptions.apps.open-cluster-management.io -p '{"metadata":{"finalizers":["finalizer.stable.example.com"]}}' --type=merge
```

Can you please provide me the command to add a dummy finalizer? I will then paste the `managedFields` per your suggestion.

Thanks.

**Comment by aviweit** [comment] 2021-09-27 20:04
@mikeshng , please find below the deployable resource output. Thanks.

```
{
  "apiVersion": "apps.open-cluster-management.io/v1",
  "kind": "Deployable",
  "metadata": {
    "annotations": {
      "apps.open-cluster-management.io/hosting-deployable": "5g-core/example-from-argo-acm-deployable",
      "apps.open-cluster-management.io/hosting-subscription": "5g-core/example-from-argo-acm",
      "apps.open-cluster-management.io/is-generated": "true",
      "apps.open-cluster-management.io/is-local-deployable": "true",
      "apps.open-cluster-management.io/managed-cluster": "paris-core/paris-core"
    },
    "creationTimestamp": "2021-09-27T20:00:51Z",
    "generateName": "example-from-argo-acm-deployable-",
    "generation": 1,
    "labels": {
      "hosting-deployable-name": "example-from-argo-acm-deployable",
      "subscription-pause": "false"
    },
    "managedFields": [
      {
        "apiVersion": "apps.open-cluster-management.io/v1",
        "fieldsType": "FieldsV1",
        "fieldsV1": {
          "f:metadata": {
            "f:annotations": {
              ".": {},
              "f:apps.open-cluster-management.io/hosting-deployable": {},
              "f:apps.open-cluster-management.io/hosting-subscription": {},
              "f:apps.open-cluster-management.io/is-generated": {},
              "f:apps.open-cluster-management.io/is-local-deployable": {},
              "f:apps.open-cluster-management.io/managed-cluster": {}
            },
            "f:generateName": {},
            "f:labels": {
              ".": {},
              "f:hosting-deployable-name": {},
              "f:subscription-pause": {}
            }
          },
          "f:spec": {
            ".": {},
            "f:template": {
              ".": {},
              "f:apiVersion": {},
              "f:kind": {},
              "f:metadata": {},
              "f:spec": {},
              "f:status": {}
            }
          },
          "f:status": {
            ".": {},
            "f:lastUpdateTime": {},
            "f:phase": {}
          }
        },
        "manager": "multicloud-operators-subscription",
        "operation": "Update",
        "time": "2021-09-27T20:00:52Z"
      }
    ],
    "name": "example-from-argo-acm-deployable-zpv62",
    "namespace": "paris-core",
    "resourceVersion": "6201345",
    "selfLink": "/apis/apps.open-cluster-management.io/v1/namespaces/paris-core/deployables/example-from-argo-acm-deployable-zpv62",
    "uid": "aec3f5bb-ea41-486c-9eda-6310eb50e3be"
  },
  "spec": {
    "template": {
      "apiVersion": "apps.open-cluster-management.io/v1",
      "kind": "Subscription",
      "metadata": {
        "annotations": {
          "apps.open-cluster-management.io/channel-generation": "1",
          "apps.open-cluster-management.io/git-branch": "main",
          "apps.open-cluster-management.io/git-path": "examples/remote-git-sub-op",
          "apps.open-cluster-management.io/hosting-subscription": "5g-core/example-from-argo-acm",
          "open-cluster-management.io/user-group": "",
          "open-cluster-management.io/user-identity": ""
        },
        "creationTimestamp": null,
        "generation": 1,
        "labels": {
          "subscription-pause": "false"
        },
        "managedFields": [
          {
            "apiVersion": "apps.open-cluster-management.io/v1",
            "fieldsType": "FieldsV1",
            "fieldsV1": {
              "f:metadata": {
                "f:annotations": {
                  ".": {},
                  "f:apps.open-cluster-management.io/github-branch": {},
                  "f:apps.open-cluster-management.io/github-path": {}
                },
                "f:ownerReferences": {
                  ".": {},
                  "k:{\"uid\":\"56db27fd-e2a2-4cee-a330-4abf1a380509\"}": {
                    ".": {},
                    "f:apiVersion": {},
                    "f:blockOwnerDeletion": {},
                    "f:controller": {},
                    "f:kind": {},
                    "f:name": {},
                    "f:uid": {}
                  }
                }
              },
              "f:spec": {
                ".": {},
                "f:channel": {},
                "f:placement": {
                  ".": {},
                  "f:clusters": {}
                }
              }
            },
            "manager": "kubectl",
            "operation": "Update",
            "time": "2021-09-27T20:00:43Z"
          }
        ],
        "name": "example-from-argo-acm",
        "namespace": "5g-core",
        "ownerReferences": [
          {
            "apiVersion": "argoproj.io/v1alpha1",
            "blockOwnerDeletion": true,
            "controller": true,
            "kind": "Workflow",
            "name": "example-from-argo-acm",
            "uid": "56db27fd-e2a2-4cee-a330-4abf1a380509"
          }
        ]
      },
      "spec": {
        "channel": "gitops-chn-ns/gitops",
        "placement": {
          "local": true
        }
      },
      "status": {
        "ansiblejobs": {},
        "lastUpdateTime": null
      }
    }
  },
  "status": {
    "lastUpdateTime": "2021-09-27T20:00:52Z",
    "phase": "Deployed"
  }
}
```

**Comment by mikeshng** [comment] 2021-09-27 20:17
I think I sort of see what the problem is. As you can see managed cluster subscription has the 
```
        "ownerReferences": [
          {
            "apiVersion": "argoproj.io/v1alpha1",
            "blockOwnerDeletion": true,
            "controller": true,
            "kind": "Workflow",
            "name": "example-from-argo-acm",
            "uid": "56db27fd-e2a2-4cee-a330-4abf1a380509"
          }
        ]
```
And since argo `Workflow` is not propagated down to the managed cluster, the subscription gets k8s garbage collected (auto deleted by k8s server) due to missing parent. 

I will look into this bug with my team and I will post the update here. Thanks for sharing your finding.

**Comment by mikeshng** [comment] 2021-09-28 15:30
@aviweit this should be fixed in the `latest` subscription image. Please give it a try and see if it works out for you. Thanks.

**Comment by aviweit** [comment] 2021-09-28 18:10
@mikeshng , I tried it by creating the Subscription with Argo installed in OCM and it works.

nginx resources had been created on the managed cluster (`paris-core`). Once I deleted Workflow CR (via `argo delete --all  -n 5g-core`) then the  Subscription CR on the hub got deleted along with the one in the managed cluster as well as the nginx resources.

Thank you.

**Comment by mikeshng** [comment] 2021-09-28 18:13
Just double checking is that the behaviour you are expecting? If it is then I am going to close this issue. Feel free to reopen if you need additional help. Thanks.

**Closed by mikeshng** 2021-09-28 18:13 UTC
Labels: bug
